FROM elixir:1.5

EXPOSE 4000

WORKDIR /code
VOLUME /code

ENV MIX_ENV development
ENV PORT 4000

COPY . .

RUN apt-get update && apt-get install -y postgresql-client

RUN \
  mix archive.install https://github.com/phoenixframework/archives/raw/master/phx_new.ez --force && \
  mix local.rebar --force && \
  mix local.hex --force && \
  mix deps.get && \
  mix compile

LABEL maintainer="Benjamin Rosas <ben.rosas@gmx.us>"

CMD mix do ecto.migrate, phx.server
